# Generated by Django 4.2.1 on 2023-05-09 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 9, 12, 4, 7, 350691, tzinfo=datetime.timezone.utc)),
        ),
    ]
